# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nhom17.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 20, 331, 51))
        self.title.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.title.setObjectName("title")
        self.input = QtWidgets.QGroupBox(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(30, 80, 741, 261))
        self.input.setObjectName("input")
        self.label_soCauHoi = QtWidgets.QLabel(self.input)
        self.label_soCauHoi.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_soCauHoi.setObjectName("label_soCauHoi")
        self.label_DAin = QtWidgets.QLabel(self.input)
        self.label_DAin.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.label_DAin.setObjectName("label_DAin")
        self.label_taiAnh = QtWidgets.QLabel(self.input)
        self.label_taiAnh.setGeometry(QtCore.QRect(30, 170, 61, 16))
        self.label_taiAnh.setObjectName("label_taiAnh")
        self.inp_soCauHoi = QtWidgets.QSpinBox(self.input)
        self.inp_soCauHoi.setGeometry(QtCore.QRect(160, 30, 42, 22))
        self.inp_soCauHoi.setObjectName("inp_soCauHoi")
        self.tb_nhapDA = QtWidgets.QTextEdit(self.input)
        self.tb_nhapDA.setGeometry(QtCore.QRect(160, 80, 551, 71))
        self.tb_nhapDA.setObjectName("tb_nhapDA")
        item = QtWidgets.QTableWidgetItem()
        self.btn_browse = QtWidgets.QPushButton(self.input)
        self.btn_browse.setGeometry(QtCore.QRect(420, 170, 75, 23))
        self.btn_browse.setStyleSheet("background-color: rgb(236, 198, 255);")
        self.btn_browse.setObjectName("btn_browse")
        self.tenAnh = QtWidgets.QLineEdit(self.input)
        self.tenAnh.setGeometry(QtCore.QRect(160, 170, 241, 21))
        self.tenAnh.setObjectName("tenAnh")
        self.btn_capNhat = QtWidgets.QPushButton(self.input)
        self.btn_capNhat.setGeometry(QtCore.QRect(230, 30, 75, 23))
        self.btn_capNhat.setStyleSheet("background-color: rgb(236, 198, 255);")
        self.btn_capNhat.setObjectName("btn_capNhat")
        self.btn_chamDiem = QtWidgets.QPushButton(self.input)
        self.btn_chamDiem.setGeometry(QtCore.QRect(300, 220, 191, 23))
        self.btn_chamDiem.setStyleSheet("background-color: rgb(236, 198, 255);")
        self.btn_chamDiem.setObjectName("btn_chamDiem")
        self.output = QtWidgets.QGroupBox(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(30, 350, 741, 221))
        self.output.setObjectName("output")
        self.label_DAout = QtWidgets.QLabel(self.output)
        self.label_DAout.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.label_DAout.setObjectName("label_DAout")
        self.label_ketQua = QtWidgets.QLabel(self.output)
        self.label_ketQua.setGeometry(QtCore.QRect(30, 160, 47, 13))
        self.label_ketQua.setObjectName("label_ketQua")
        self.tb_DAout = QtWidgets.QTextEdit(self.output)
        self.tb_DAout.setGeometry(QtCore.QRect(160, 50, 551, 71))
        self.tb_DAout.setObjectName("tb_DAout")
        item = QtWidgets.QTableWidgetItem()
        self.Diem = QtWidgets.QLabel(self.output)
        self.Diem.setGeometry(QtCore.QRect(350, 160, 91, 31))
        self.Diem.setObjectName("Diem")
        self.btn_chamLai = QtWidgets.QPushButton(self.output)
        self.btn_chamLai.setGeometry(QtCore.QRect(640, 130, 75, 23))
        self.btn_chamLai.setStyleSheet("background-color: rgb(236, 198, 255);")
        self.btn_chamLai.setObjectName("btn_chamLai")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nhom17"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#00557f;\">Chấm phiếu điền trắc nghiệm</span></p></body></html>"))
        self.input.setTitle(_translate("MainWindow", "Input"))
        self.label_soCauHoi.setText(_translate("MainWindow", "Nhập số câu hỏi"))
        self.label_DAin.setText(_translate("MainWindow", "Nhập đáp án đúng"))
        self.label_taiAnh.setText(_translate("MainWindow", "Tải ảnh lên"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.btn_capNhat.setText(_translate("MainWindow", "Cập nhật"))
        self.btn_chamDiem.setText(_translate("MainWindow", "Chấm điểm"))
        self.output.setTitle(_translate("MainWindow", "Output"))
        self.label_DAout.setText(_translate("MainWindow", "Đáp án"))
        self.label_ketQua.setText(_translate("MainWindow", "Kết quả"))
        self.Diem.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Điểm số</span></p></body></html>"))
        self.btn_chamLai.setText(_translate("MainWindow", "Chấm lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
